[build.environment]
  PYTHON_VERSION = "3.11"

[functions]
  directory = "netlify/functions/"

# Redirect rule to proxy /api/* calls to the corresponding function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200 # Use 200 for a rewrite (proxy) 