[build.environment]
  PYTHON_VERSION = "3.11"

[functions]
  directory = "netlify/functions/"
  # Explicitly include the function
  included_files = ["netlify/functions/hello.py"]

[[plugins]]
package = "@netlify/plugin-functions-core" 